import { useState } from "react";
import { FileSpreadsheet, Download, Info, Eye, X, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { exportMultiSheet, formatDateGST } from "@/lib/export-utils";
import { fetchCompanySettings } from "@/lib/settings-api";
import { format, startOfMonth, endOfMonth, subMonths, startOfQuarter, endOfQuarter } from "date-fns";

// ── Types ─────────────────────────────────────────────────────────────────────

type DateRange = "this_month" | "last_month" | "this_quarter" | "this_fy";

export interface PreviewSheet {
  name: string;
  headers: string[];
  rows: (string | number | null)[][];
  totalRows: number;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

const DISCLAIMER = "Generated by BizDocs — verify before filing. This file is for reference only.";

function round2(n: number): number {
  return Math.round((n ?? 0) * 100) / 100;
}

function extractStateCode(pos: string | null | undefined): string {
  if (!pos) return "";
  const m = pos.match(/^(\d{2})/);
  return m ? m[1] : pos.slice(0, 2);
}

function getDateBounds(
  range: DateRange,
  fyYear: string | null
): { start: string; end: string; label: string } {
  const now = new Date();
  if (range === "this_month") {
    return {
      start: format(startOfMonth(now), "yyyy-MM-dd"),
      end: format(now, "yyyy-MM-dd"),
      label: format(now, "MMMM yyyy"),
    };
  }
  if (range === "last_month") {
    const prev = subMonths(now, 1);
    return {
      start: format(startOfMonth(prev), "yyyy-MM-dd"),
      end: format(endOfMonth(prev), "yyyy-MM-dd"),
      label: format(prev, "MMMM yyyy"),
    };
  }
  if (range === "this_quarter") {
    return {
      start: format(startOfQuarter(now), "yyyy-MM-dd"),
      end: format(now, "yyyy-MM-dd"),
      label: `Q${Math.ceil((now.getMonth() + 1) / 3)} ${now.getFullYear()}`,
    };
  }
  // this_fy — use company FY if available
  if (fyYear && /^\d{2}-\d{2}$/.test(fyYear)) {
    const startYear = 2000 + parseInt(fyYear.slice(0, 2));
    const endYear = startYear + 1;
    return {
      start: `${startYear}-04-01`,
      end: `${endYear}-03-31`,
      label: `FY ${fyYear}`,
    };
  }
  const fy = now.getMonth() >= 3 ? now.getFullYear() : now.getFullYear() - 1;
  return {
    start: `${fy}-04-01`,
    end: format(now, "yyyy-MM-dd"),
    label: `FY ${String(fy).slice(2)}-${String(fy + 1).slice(2)}`,
  };
}

function slugLabel(label: string): string {
  return label.replace(/\s+/g, "").replace(/[^A-Za-z0-9]/g, "");
}

// ── Data Builders ─────────────────────────────────────────────────────────────

async function buildGstr1Data(start: string, end: string, companyStateCode: string) {
  const { data: invoices } = await supabase
    .from("invoices")
    .select("id, invoice_number, invoice_date, customer_name, customer_gstin, place_of_supply, grand_total")
    .gte("invoice_date", start)
    .lte("invoice_date", end)
    .not("status", "in", "(cancelled,deleted)")
    .order("invoice_date", { ascending: true });

  const invData = (invoices ?? []) as any[];
  const invIds = invData.map((i) => i.id);
  let lineItems: any[] = [];
  if (invIds.length > 0) {
    const { data: li } = await (supabase as any)
      .from("invoice_line_items")
      .select("invoice_id, hsn_sac_code, description, unit, quantity, gst_rate, taxable_amount, cgst_amount, sgst_amount, igst_amount, line_total")
      .in("invoice_id", invIds);
    lineItems = li ?? [];
  }

  const invMap = new Map<string, any>(invData.map((i) => [i.id, i]));

  const b2bMap = new Map<string, any>();
  const b2cLargeMap = new Map<string, any>();
  const hsnMap = new Map<string, any>();
  const nilAggMap = new Map<string, { type: string; nil_rated: number; exempted: number; non_gst: number }>();

  for (const li of lineItems) {
    const inv = invMap.get(li.invoice_id);
    if (!inv) continue;

    const posCode = extractStateCode(inv.place_of_supply);
    const isB2B = !!(inv.customer_gstin?.trim());
    const isInterState = posCode !== companyStateCode;
    const rate = li.gst_rate ?? 0;
    const taxable = round2(li.taxable_amount ?? 0);

    // B2B
    if (isB2B) {
      const key = `${li.invoice_id}|${rate}`;
      if (!b2bMap.has(key)) {
        b2bMap.set(key, {
          gstin: inv.customer_gstin ?? "",
          name: inv.customer_name ?? "",
          invoice_number: inv.invoice_number ?? "",
          invoice_date: formatDateGST(inv.invoice_date),
          invoice_value: round2(inv.grand_total ?? 0),
          place_of_supply: posCode || inv.place_of_supply || "",
          reverse_charge: "N",
          invoice_type: "Regular",
          ecomm_gstin: "",
          rate,
          taxable_value: 0,
          cess_amount: 0,
        });
      }
      b2bMap.get(key).taxable_value += taxable;
    }

    // B2C Large (inter-state B2C with invoice value > 2.5 lakh)
    if (!isB2B && isInterState && (inv.grand_total ?? 0) > 250000) {
      const key = `${posCode}|${rate}`;
      if (!b2cLargeMap.has(key)) {
        b2cLargeMap.set(key, {
          type: "OE",
          place_of_supply: posCode || inv.place_of_supply || "",
          applicable_pct: "",
          rate,
          taxable_value: 0,
          cess_amount: 0,
          ecomm_gstin: "",
        });
      }
      b2cLargeMap.get(key).taxable_value += taxable;
    }

    // HSN Summary
    const hsnKey = `${li.hsn_sac_code ?? ""}|${rate}`;
    if (!hsnMap.has(hsnKey)) {
      hsnMap.set(hsnKey, {
        hsn: li.hsn_sac_code ?? "",
        description: li.description ?? "",
        uqc: li.unit ?? "NOS",
        total_quantity: 0,
        total_value: 0,
        taxable_value: 0,
        integrated_tax: 0,
        central_tax: 0,
        state_ut_tax: 0,
        cess: 0,
      });
    }
    const hsnRow = hsnMap.get(hsnKey);
    hsnRow.total_quantity += li.quantity ?? 0;
    hsnRow.total_value += round2(li.line_total ?? 0);
    hsnRow.taxable_value += taxable;
    hsnRow.integrated_tax += round2(li.igst_amount ?? 0);
    hsnRow.central_tax += round2(li.cgst_amount ?? 0);
    hsnRow.state_ut_tax += round2(li.sgst_amount ?? 0);

    // Nil / Zero-rated
    if (rate === 0 && taxable > 0) {
      const nilKey = isB2B ? "B2B" : "B2C";
      if (!nilAggMap.has(nilKey)) {
        nilAggMap.set(nilKey, { type: nilKey, nil_rated: 0, exempted: 0, non_gst: 0 });
      }
      nilAggMap.get(nilKey)!.nil_rated += taxable;
    }
  }

  const b2b = [...b2bMap.values()].map((r) => ({ ...r, taxable_value: round2(r.taxable_value) }));
  const b2cLarge = [...b2cLargeMap.values()].map((r) => ({ ...r, taxable_value: round2(r.taxable_value) }));
  const hsn = [...hsnMap.values()].map((r) => ({
    ...r,
    total_value: round2(r.total_value),
    taxable_value: round2(r.taxable_value),
    integrated_tax: round2(r.integrated_tax),
    central_tax: round2(r.central_tax),
    state_ut_tax: round2(r.state_ut_tax),
  }));
  const nil = [...nilAggMap.values()].map((r) => ({
    ...r,
    nil_rated: round2(r.nil_rated),
  }));

  return { b2b, b2cLarge, hsn, nil };
}

async function buildGstr2Data(start: string, end: string, companyStateCode: string) {
  // Use purchase orders as the base source (they have the complete GST data)
  const { data: pos } = await supabase
    .from("purchase_orders")
    .select("id, po_number, po_date, vendor_name, vendor_gstin, vendor_state_code, grand_total")
    .gte("po_date", start)
    .lte("po_date", end)
    .not("status", "in", "(cancelled,deleted)")
    .order("po_date", { ascending: true });

  const poData = (pos ?? []) as any[];
  const poIds = poData.map((p) => p.id);

  // Fetch the vendor_invoice_number from linked GRNs (best effort)
  const grnInvMap = new Map<string, { invoice_number: string; invoice_date: string }>();
  if (poIds.length > 0) {
    const { data: grns } = await (supabase as any)
      .from("grns")
      .select("po_id, vendor_invoice_number, vendor_invoice_date")
      .in("po_id", poIds)
      .not("status", "in", "(cancelled,deleted)");
    for (const g of (grns ?? []) as any[]) {
      if (g.po_id && g.vendor_invoice_number) {
        grnInvMap.set(g.po_id, {
          invoice_number: g.vendor_invoice_number,
          invoice_date: g.vendor_invoice_date || "",
        });
      }
    }
  }

  let lineItems: any[] = [];
  if (poIds.length > 0) {
    const { data: li } = await (supabase as any)
      .from("po_line_items")
      .select("po_id, description, quantity, unit_price, gst_rate, line_total")
      .in("po_id", poIds);
    lineItems = li ?? [];
  }

  const poMap = new Map<string, any>(poData.map((p) => [p.id, p]));

  // Group by PO + rate
  const rowMap = new Map<string, any>();
  for (const li of lineItems) {
    const po = poMap.get(li.po_id);
    if (!po) continue;

    const rate = li.gst_rate ?? 0;
    const key = `${li.po_id}|${rate}`;
    const taxable = round2(li.line_total ?? (li.quantity ?? 0) * (li.unit_price ?? 0));
    const vendorStateCode = extractStateCode(po.vendor_gstin) || po.vendor_state_code || "";
    const isInterState = vendorStateCode !== companyStateCode;
    const gstAmt = round2(taxable * (rate / 100));
    const igst = isInterState ? gstAmt : 0;
    const cgst = isInterState ? 0 : round2(gstAmt / 2);
    const sgst = isInterState ? 0 : round2(gstAmt / 2);
    const grnInfo = grnInvMap.get(li.po_id);

    if (!rowMap.has(key)) {
      rowMap.set(key, {
        gstin_supplier: po.vendor_gstin ?? "",
        supplier_name: po.vendor_name ?? "",
        invoice_number: grnInfo?.invoice_number || po.po_number || "",
        invoice_date: formatDateGST(grnInfo?.invoice_date || po.po_date),
        invoice_value: round2(po.grand_total ?? 0),
        place_of_supply: companyStateCode,
        reverse_charge: "N",
        invoice_type: "Regular",
        rate,
        taxable_value: 0,
        integrated_tax: 0,
        central_tax: 0,
        state_ut_tax: 0,
        cess: 0,
        eligibility: "Input",
        availed_igst: 0,
        availed_cgst: 0,
        availed_sgst: 0,
        availed_cess: 0,
      });
    }
    const row = rowMap.get(key);
    row.taxable_value += taxable;
    row.integrated_tax += igst;
    row.central_tax += cgst;
    row.state_ut_tax += sgst;
    row.availed_igst += igst;
    row.availed_cgst += cgst;
    row.availed_sgst += sgst;
  }

  return [...rowMap.values()].map((r) => ({
    ...r,
    taxable_value: round2(r.taxable_value),
    integrated_tax: round2(r.integrated_tax),
    central_tax: round2(r.central_tax),
    state_ut_tax: round2(r.state_ut_tax),
    availed_igst: round2(r.availed_igst),
    availed_cgst: round2(r.availed_cgst),
    availed_sgst: round2(r.availed_sgst),
  }));
}

async function buildHsnData(start: string, end: string) {
  const { data: invs } = await supabase
    .from("invoices")
    .select("id")
    .gte("invoice_date", start)
    .lte("invoice_date", end)
    .not("status", "in", "(cancelled,deleted)");

  const invIds = (invs ?? []).map((i: any) => i.id);
  if (invIds.length === 0) return [];

  const { data: li } = await (supabase as any)
    .from("invoice_line_items")
    .select("hsn_sac_code, description, unit, quantity, taxable_amount, cgst_amount, sgst_amount, igst_amount, line_total")
    .in("invoice_id", invIds);

  const hsnMap = new Map<string, any>();
  for (const row of (li ?? []) as any[]) {
    const key = row.hsn_sac_code ?? "";
    if (!hsnMap.has(key)) {
      hsnMap.set(key, {
        hsn: key,
        description: row.description ?? "",
        uqc: row.unit ?? "NOS",
        total_quantity: 0,
        total_value: 0,
        taxable_value: 0,
        integrated_tax: 0,
        central_tax: 0,
        state_ut_tax: 0,
        cess: 0,
      });
    }
    const r = hsnMap.get(key);
    r.total_quantity += row.quantity ?? 0;
    r.total_value += round2(row.line_total ?? 0);
    r.taxable_value += round2(row.taxable_amount ?? 0);
    r.integrated_tax += round2(row.igst_amount ?? 0);
    r.central_tax += round2(row.cgst_amount ?? 0);
    r.state_ut_tax += round2(row.sgst_amount ?? 0);
  }

  return [...hsnMap.values()].map((r) => ({
    ...r,
    total_value: round2(r.total_value),
    taxable_value: round2(r.taxable_value),
    integrated_tax: round2(r.integrated_tax),
    central_tax: round2(r.central_tax),
    state_ut_tax: round2(r.state_ut_tax),
  }));
}

async function buildItcData(start: string, end: string) {
  const { data: grns } = await (supabase as any)
    .from("grns")
    .select("id, grn_number, grn_date, vendor_name, vendor_invoice_number, vendor_invoice_date, po_id")
    .gte("grn_date", start)
    .lte("grn_date", end)
    .not("status", "in", "(cancelled,deleted,draft)");

  const grnData = (grns ?? []) as any[];
  const poIds = [...new Set(grnData.map((g) => g.po_id).filter(Boolean))];

  const poMap = new Map<string, any>();
  if (poIds.length > 0) {
    const { data: pos } = await supabase
      .from("purchase_orders")
      .select("id, vendor_name, vendor_gstin, grand_total, igst_amount, cgst_amount, sgst_amount")
      .in("id", poIds as string[]);
    for (const po of (pos ?? []) as any[]) poMap.set(po.id, po);
  }

  return grnData.map((grn) => {
    const po = poMap.get(grn.po_id) ?? {};
    return {
      grn_number: grn.grn_number ?? "",
      grn_date: formatDateGST(grn.grn_date),
      vendor_name: po.vendor_name || grn.vendor_name || "",
      vendor_gstin: po.vendor_gstin ?? "",
      vendor_invoice: grn.vendor_invoice_number ?? "",
      invoice_date: formatDateGST(grn.vendor_invoice_date),
      invoice_value: round2(po.grand_total ?? 0),
      igst: round2(po.igst_amount ?? 0),
      cgst: round2(po.cgst_amount ?? 0),
      sgst: round2(po.sgst_amount ?? 0),
      total_itc: round2((po.igst_amount ?? 0) + (po.cgst_amount ?? 0) + (po.sgst_amount ?? 0)),
    };
  });
}

// ── Sheet definitions ─────────────────────────────────────────────────────────

const GSTR1_B2B_HEADERS = [
  "GSTIN of Recipient", "Receiver Name", "Invoice Number", "Invoice Date",
  "Invoice Value", "Place of Supply", "Reverse Charge", "Invoice Type",
  "E-Commerce GSTIN", "Rate", "Taxable Value", "Cess Amount",
];

const GSTR1_B2CLARGE_HEADERS = [
  "Type", "Place of Supply", "Applicable % of Tax Rate",
  "Rate", "Taxable Value", "Cess Amount", "E-Commerce GSTIN",
];

const HSN_HEADERS = [
  "HSN", "Description", "UQC", "Total Quantity", "Total Value",
  "Taxable Value", "Integrated Tax", "Central Tax", "State/UT Tax", "Cess",
];

const NIL_HEADERS = ["Type", "Nil Rated Supplies", "Exempted", "Non-GST"];

const GSTR2_B2B_HEADERS = [
  "GSTIN of Supplier", "Supplier Name", "Invoice Number", "Invoice Date",
  "Invoice Value", "Place of Supply", "Reverse Charge", "Invoice Type",
  "Rate", "Taxable Value", "Integrated Tax", "Central Tax", "State/UT Tax",
  "Cess", "Eligibility", "Availed ITC Integrated", "Availed ITC Central",
  "Availed ITC State", "Availed ITC Cess",
];

function b2bToRow(r: any): (string | number)[] {
  return [r.gstin, r.name, r.invoice_number, r.invoice_date, r.invoice_value,
    r.place_of_supply, r.reverse_charge, r.invoice_type, r.ecomm_gstin,
    r.rate, r.taxable_value, r.cess_amount];
}
function b2cToRow(r: any): (string | number)[] {
  return [r.type, r.place_of_supply, r.applicable_pct, r.rate, r.taxable_value, r.cess_amount, r.ecomm_gstin];
}
function hsnToRow(r: any): (string | number)[] {
  return [r.hsn, r.description, r.uqc, r.total_quantity, r.total_value,
    r.taxable_value, r.integrated_tax, r.central_tax, r.state_ut_tax, r.cess];
}
function nilToRow(r: any): (string | number)[] {
  return [r.type, r.nil_rated, r.exempted, r.non_gst];
}
function gstr2ToRow(r: any): (string | number)[] {
  return [r.gstin_supplier, r.supplier_name, r.invoice_number, r.invoice_date,
    r.invoice_value, r.place_of_supply, r.reverse_charge, r.invoice_type,
    r.rate, r.taxable_value, r.integrated_tax, r.central_tax, r.state_ut_tax,
    r.cess, r.eligibility, r.availed_igst, r.availed_cgst, r.availed_sgst, r.availed_cess];
}

// Convert sheet data into exportMultiSheet format
function toExportSheet(name: string, headers: string[], rows: (string | number)[][], widths?: number[]) {
  const data = rows.map((row) => {
    const obj: Record<string, any> = {};
    headers.forEach((h, i) => { obj[h] = row[i] ?? ""; });
    return obj;
  });
  const columns = headers.map((h, i) => ({
    key: h,
    label: h,
    width: widths?.[i] ?? Math.max(h.length + 2, 14),
  }));
  return { sheetName: name, columns, data };
}

// ── Preview Dialog ────────────────────────────────────────────────────────────

function PreviewDialog({
  open,
  onClose,
  title,
  sheets,
}: {
  open: boolean;
  onClose: () => void;
  title: string;
  sheets: PreviewSheet[];
}) {
  const [activeTab, setActiveTab] = useState(0);
  const sheet = sheets[activeTab];
  const PREVIEW_LIMIT = 50;

  return (
    <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="max-w-6xl w-full max-h-[85vh] flex flex-col p-0">
        <DialogHeader className="px-6 pt-5 pb-3 border-b border-border shrink-0">
          <div className="flex items-center justify-between">
            <DialogTitle className="text-base font-semibold">{title} — Preview</DialogTitle>
            <button onClick={onClose} className="text-muted-foreground hover:text-foreground">
              <X className="h-4 w-4" />
            </button>
          </div>
          {sheets.length > 1 && (
            <div className="flex gap-1 mt-2 flex-wrap">
              {sheets.map((s, i) => (
                <button
                  key={s.name}
                  onClick={() => setActiveTab(i)}
                  className={`text-xs px-3 py-1 rounded-full border transition-colors ${
                    i === activeTab
                      ? "bg-blue-600 text-white border-blue-600"
                      : "border-border text-muted-foreground hover:text-foreground"
                  }`}
                >
                  {s.name}
                </button>
              ))}
            </div>
          )}
        </DialogHeader>

        {sheet && (
          <div className="flex-1 overflow-auto p-4">
            <div className="flex items-center justify-between mb-2">
              <p className="text-xs text-muted-foreground">
                Showing first {Math.min(sheet.rows.length, PREVIEW_LIMIT)} of {sheet.totalRows} rows
              </p>
              <p className="text-xs text-amber-600 font-medium">{DISCLAIMER}</p>
            </div>
            <div className="overflow-x-auto rounded-lg border border-border">
              <table className="w-full text-xs">
                <thead className="bg-slate-800 text-white">
                  <tr>
                    {sheet.headers.map((h) => (
                      <th key={h} className="px-2 py-1.5 text-left whitespace-nowrap font-medium">
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {sheet.rows.slice(0, PREVIEW_LIMIT).map((row, i) => (
                    <tr key={i} className={i % 2 === 0 ? "bg-white" : "bg-slate-50"}>
                      {row.map((cell, j) => (
                        <td key={j} className="px-2 py-1 border-b border-border/50 whitespace-nowrap">
                          {cell ?? ""}
                        </td>
                      ))}
                    </tr>
                  ))}
                  {sheet.rows.length === 0 && (
                    <tr>
                      <td colSpan={sheet.headers.length} className="text-center py-8 text-muted-foreground">
                        No data for this period
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

// ── Report Card ───────────────────────────────────────────────────────────────

interface ReportCardProps {
  icon: React.ReactNode;
  title: string;
  description: string;
  onDownload: (range: DateRange) => Promise<void>;
  onPreview: (range: DateRange) => Promise<PreviewSheet[]>;
}

function ReportCard({ icon, title, description, onDownload, onPreview }: ReportCardProps) {
  const [range, setRange] = useState<DateRange>("this_month");
  const [loading, setLoading] = useState(false);
  const [previewing, setPreviewing] = useState(false);
  const [previewSheets, setPreviewSheets] = useState<PreviewSheet[]>([]);
  const [previewOpen, setPreviewOpen] = useState(false);

  const handleDownload = async () => {
    setLoading(true);
    try { await onDownload(range); } finally { setLoading(false); }
  };

  const handlePreview = async () => {
    setPreviewing(true);
    try {
      const sheets = await onPreview(range);
      setPreviewSheets(sheets);
      setPreviewOpen(true);
    } finally {
      setPreviewing(false);
    }
  };

  return (
    <>
      <div className="paper-card flex flex-col gap-4">
        <div className="flex items-start gap-3">
          <div className="rounded-lg bg-blue-50 p-2 shrink-0">{icon}</div>
          <div>
            <h3 className="font-semibold text-slate-900 text-sm">{title}</h3>
            <p className="text-xs text-muted-foreground mt-0.5 leading-relaxed">{description}</p>
          </div>
        </div>
        <div className="flex items-center gap-2 mt-auto flex-wrap">
          <Select value={range} onValueChange={(v) => setRange(v as DateRange)}>
            <SelectTrigger className="h-8 text-xs flex-1 min-w-[110px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="this_month">This Month</SelectItem>
              <SelectItem value="last_month">Last Month</SelectItem>
              <SelectItem value="this_quarter">This Quarter</SelectItem>
              <SelectItem value="this_fy">This Financial Year</SelectItem>
            </SelectContent>
          </Select>
          <Button
            size="sm"
            variant="outline"
            className="h-8 gap-1.5 shrink-0"
            onClick={handlePreview}
            disabled={previewing || loading}
          >
            <Eye className="h-3.5 w-3.5" />
            {previewing ? "Loading…" : "Preview"}
          </Button>
          <Button
            size="sm"
            className="h-8 gap-1.5 bg-blue-600 hover:bg-blue-700 text-white shrink-0"
            onClick={handleDownload}
            disabled={loading || previewing}
          >
            <Download className="h-3.5 w-3.5" />
            {loading ? "Generating…" : "Download"}
          </Button>
        </div>
      </div>

      <PreviewDialog
        open={previewOpen}
        onClose={() => setPreviewOpen(false)}
        title={title}
        sheets={previewSheets}
      />
    </>
  );
}

// ── Main Page ─────────────────────────────────────────────────────────────────

export default function GstReports() {
  const { toast } = useToast();

  const { data: companySettings } = useQuery({
    queryKey: ["company-settings"],
    queryFn: fetchCompanySettings,
  });

  const fyYear = companySettings?.fy_year ?? null;
  const companyStateCode = companySettings?.state_code ?? "";

  const handleError = (title: string) => {
    toast({ title, description: "Check console for details.", variant: "destructive" });
  };

  // ── GSTR-1 ────────────────────────────────────────────────────────────────

  const previewGstr1 = async (range: DateRange): Promise<PreviewSheet[]> => {
    const { start, end } = getDateBounds(range, fyYear);
    const { b2b, b2cLarge, hsn, nil } = await buildGstr1Data(start, end, companyStateCode);
    return [
      { name: "B2B Invoices", headers: GSTR1_B2B_HEADERS, rows: b2b.map(b2bToRow), totalRows: b2b.length },
      { name: "B2C Large", headers: GSTR1_B2CLARGE_HEADERS, rows: b2cLarge.map(b2cToRow), totalRows: b2cLarge.length },
      { name: "HSN Summary", headers: HSN_HEADERS, rows: hsn.map(hsnToRow), totalRows: hsn.length },
      { name: "Nil/Exempt", headers: NIL_HEADERS, rows: nil.map(nilToRow), totalRows: nil.length },
    ];
  };

  const downloadGstr1 = async (range: DateRange) => {
    try {
      const { start, end, label } = getDateBounds(range, fyYear);
      const { b2b, b2cLarge, hsn, nil } = await buildGstr1Data(start, end, companyStateCode);
      exportMultiSheet(
        [
          toExportSheet("B2B Invoices", GSTR1_B2B_HEADERS, b2b.map(b2bToRow)),
          toExportSheet("B2C Large", GSTR1_B2CLARGE_HEADERS, b2cLarge.map(b2cToRow)),
          toExportSheet("HSN Summary", HSN_HEADERS, hsn.map(hsnToRow)),
          toExportSheet("Nil-Exempt-NonGST", NIL_HEADERS, nil.map(nilToRow)),
        ],
        `BizDocs_GSTR1_${slugLabel(label)}.xlsx`,
        DISCLAIMER
      );
    } catch { handleError("Failed to generate GSTR-1"); }
  };

  // ── GSTR-2 ────────────────────────────────────────────────────────────────

  const previewGstr2 = async (range: DateRange): Promise<PreviewSheet[]> => {
    const { start, end } = getDateBounds(range, fyYear);
    const rows = await buildGstr2Data(start, end, companyStateCode);
    return [{ name: "B2B Purchases", headers: GSTR2_B2B_HEADERS, rows: rows.map(gstr2ToRow), totalRows: rows.length }];
  };

  const downloadGstr2 = async (range: DateRange) => {
    try {
      const { start, end, label } = getDateBounds(range, fyYear);
      const rows = await buildGstr2Data(start, end, companyStateCode);
      exportMultiSheet(
        [toExportSheet("B2B Purchases", GSTR2_B2B_HEADERS, rows.map(gstr2ToRow))],
        `BizDocs_GSTR2_${slugLabel(label)}.xlsx`,
        DISCLAIMER
      );
    } catch { handleError("Failed to generate GSTR-2"); }
  };

  // ── HSN Summary ───────────────────────────────────────────────────────────

  const previewHsn = async (range: DateRange): Promise<PreviewSheet[]> => {
    const { start, end } = getDateBounds(range, fyYear);
    const rows = await buildHsnData(start, end);
    return [{ name: "HSN Summary", headers: HSN_HEADERS, rows: rows.map(hsnToRow), totalRows: rows.length }];
  };

  const downloadHsn = async (range: DateRange) => {
    try {
      const { start, end, label } = getDateBounds(range, fyYear);
      const rows = await buildHsnData(start, end);
      if (rows.length === 0) { toast({ title: "No invoices in this period" }); return; }
      exportMultiSheet(
        [toExportSheet("HSN Summary", HSN_HEADERS, rows.map(hsnToRow))],
        `BizDocs_HSN_${slugLabel(label)}.xlsx`,
        DISCLAIMER
      );
    } catch { handleError("Failed to generate HSN Summary"); }
  };

  // ── ITC Register ──────────────────────────────────────────────────────────

  const ITC_HEADERS = [
    "GRN Number", "GRN Date", "Vendor Name", "Vendor GSTIN",
    "Vendor Invoice", "Invoice Date", "Invoice Value",
    "IGST", "CGST", "SGST", "Total ITC",
  ];
  const itcToRow = (r: any): (string | number)[] => [
    r.grn_number, r.grn_date, r.vendor_name, r.vendor_gstin,
    r.vendor_invoice, r.invoice_date, r.invoice_value,
    r.igst, r.cgst, r.sgst, r.total_itc,
  ];

  const previewItc = async (range: DateRange): Promise<PreviewSheet[]> => {
    const { start, end } = getDateBounds(range, fyYear);
    const rows = await buildItcData(start, end);
    return [{ name: "ITC Register", headers: ITC_HEADERS, rows: rows.map(itcToRow), totalRows: rows.length }];
  };

  const downloadItc = async (range: DateRange) => {
    try {
      const { start, end, label } = getDateBounds(range, fyYear);
      const rows = await buildItcData(start, end);
      exportMultiSheet(
        [toExportSheet("ITC Register", ITC_HEADERS, rows.map(itcToRow))],
        `BizDocs_ITC_${slugLabel(label)}.xlsx`,
        DISCLAIMER
      );
    } catch { handleError("Failed to generate ITC Register"); }
  };

  // ── E-way Bill ────────────────────────────────────────────────────────────

  const EWAY_HEADERS = [
    "DC No", "Date", "Party Name", "GSTIN",
    "From State", "To State", "Description", "HSN", "Qty", "Value", "Vehicle No",
  ];

  const previewEway = async (range: DateRange): Promise<PreviewSheet[]> => {
    const rows = await fetchEwayRows(range);
    return [{ name: "E-way Bill Data", headers: EWAY_HEADERS, rows, totalRows: rows.length }];
  };

  const downloadEway = async (range: DateRange) => {
    try {
      const { label } = getDateBounds(range, fyYear);
      const rows = await fetchEwayRows(range);
      exportMultiSheet(
        [toExportSheet("E-way Bill Data", EWAY_HEADERS, rows)],
        `BizDocs_EwayBill_${slugLabel(label)}.xlsx`,
        DISCLAIMER
      );
    } catch { handleError("Failed to generate E-way Bill data"); }
  };

  const fetchEwayRows = async (range: DateRange) => {
    const { start, end } = getDateBounds(range, fyYear);
    const { data: dcs } = await supabase
      .from("delivery_challans")
      .select("id, dc_number, dc_date, party_name, party_gstin, vehicle_number")
      .gte("dc_date", start)
      .lte("dc_date", end)
      .neq("status", "cancelled")
      .order("dc_date", { ascending: true });

    const dcData = (dcs ?? []) as any[];
    const dcIds = dcData.map((d) => d.id);
    let lineItems: any[] = [];
    if (dcIds.length > 0) {
      const { data: li } = await (supabase as any)
        .from("dc_line_items")
        .select("dc_id, description, hsn_sac_code, qty_nos, approximate_value")
        .in("dc_id", dcIds);
      lineItems = li ?? [];
    }

    const dcMap = new Map(dcData.map((d) => [d.id, d]));
    return lineItems.map((li): (string | number)[] => {
      const dc = dcMap.get(li.dc_id) as any;
      return [
        dc?.dc_number ?? "", formatDateGST(dc?.dc_date),
        dc?.party_name ?? "", dc?.party_gstin ?? "",
        "", "",  // from_state, to_state — not in table
        li.description ?? "", li.hsn_sac_code ?? "",
        li.qty_nos ?? 0, li.approximate_value ?? 0,
        dc?.vehicle_number ?? "",
      ];
    });
  };

  // ── Job Work ──────────────────────────────────────────────────────────────

  const JW_HEADERS = [
    "DC No", "Date", "Vendor Name", "Vendor GSTIN",
    "Component", "Qty Sent", "Qty Returned", "Pending Qty", "Days Out",
  ];

  const previewJobWork = async (range: DateRange): Promise<PreviewSheet[]> => {
    const rows = await fetchJobWorkRows(range);
    return [{ name: "Job Work Register", headers: JW_HEADERS, rows, totalRows: rows.length }];
  };

  const downloadJobWork = async (range: DateRange) => {
    try {
      const { label } = getDateBounds(range, fyYear);
      const rows = await fetchJobWorkRows(range);
      exportMultiSheet(
        [toExportSheet("Job Work Register", JW_HEADERS, rows)],
        `BizDocs_JobWork_${slugLabel(label)}.xlsx`,
        DISCLAIMER
      );
    } catch { handleError("Failed to generate Job Work Register"); }
  };

  const fetchJobWorkRows = async (range: DateRange) => {
    const { start, end } = getDateBounds(range, fyYear);
    const { data: dcs } = await supabase
      .from("delivery_challans")
      .select("id, dc_number, dc_date, party_name, party_gstin, return_due_date, status")
      .eq("dc_type" as any, "returnable")
      .gte("dc_date", start)
      .lte("dc_date", end)
      .order("dc_date", { ascending: true });

    const dcData = (dcs ?? []) as any[];
    const dcIds = dcData.map((d) => d.id);
    let lineItems: any[] = [];
    if (dcIds.length > 0) {
      const { data: li } = await (supabase as any)
        .from("dc_line_items")
        .select("dc_id, description, qty_nos, returned_qty_nos")
        .in("dc_id", dcIds);
      lineItems = li ?? [];
    }

    const dcMap = new Map(dcData.map((d) => [d.id, d]));
    return lineItems.map((li): (string | number)[] => {
      const dc = dcMap.get(li.dc_id) as any;
      const sent = li.qty_nos ?? 0;
      const returned = li.returned_qty_nos ?? 0;
      const daysOut = dc?.dc_date
        ? Math.max(0, Math.floor((Date.now() - new Date(dc.dc_date).getTime()) / 86400000))
        : 0;
      return [
        dc?.dc_number ?? "", formatDateGST(dc?.dc_date),
        dc?.party_name ?? "", dc?.party_gstin ?? "",
        li.description ?? "", sent, returned, Math.max(0, sent - returned), daysOut,
      ];
    });
  };

  // ── Render ────────────────────────────────────────────────────────────────

  const cardIcon = <FileSpreadsheet className="h-4 w-4 text-blue-600" />;

  return (
    <div className="p-4 md:p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
          <FileSpreadsheet className="h-5 w-5 text-blue-600" />
          GST Reports
        </h1>
        <p className="text-sm text-slate-500 mt-1">
          GST portal-compliant Excel files · FY {fyYear ?? "—"} · State: {companyStateCode || "—"}
        </p>
      </div>

      <div className="flex items-start gap-3 bg-blue-50 border border-blue-200 rounded-lg p-4 text-blue-800 text-sm">
        <Info className="h-4 w-4 shrink-0 mt-0.5 text-blue-600" />
        <p>
          Reports match GST portal column formats. Use <strong>Preview</strong> to verify before downloading.
          Always reconcile with your CA before filing.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <ReportCard
          icon={cardIcon}
          title="GSTR-1 (Outward Supplies)"
          description="4-sheet portal-format file: B2B invoices, B2C Large, HSN Summary, Nil/Exempt. One row per invoice per rate."
          onDownload={downloadGstr1}
          onPreview={previewGstr1}
        />
        <ReportCard
          icon={cardIcon}
          title="GSTR-2 / ITC (Inward Supplies)"
          description="B2B purchase register with all 19 portal columns: supplier GSTIN, invoice details, rate-wise ITC breakup."
          onDownload={downloadGstr2}
          onPreview={previewGstr2}
        />
        <ReportCard
          icon={cardIcon}
          title="HSN Summary"
          description="Standalone HSN summary with quantity, total value, taxable value, IGST, CGST, SGST and Cess."
          onDownload={downloadHsn}
          onPreview={previewHsn}
        />
        <ReportCard
          icon={cardIcon}
          title="ITC Register (GRN-based)"
          description="Input tax credit register built from received GRNs. Shows vendor invoice details and ITC amounts per receipt."
          onDownload={downloadItc}
          onPreview={previewItc}
        />
        <ReportCard
          icon={cardIcon}
          title="E-way Bill Data"
          description="DC data formatted for e-way bill reference. Includes HSN, vehicle number, party GSTIN and values."
          onDownload={downloadEway}
          onPreview={previewEway}
        />
        <ReportCard
          icon={cardIcon}
          title="Job Work Register (Section 143)"
          description="All returnable DC components sent for job work — quantity sent, returned, pending, and days outstanding."
          onDownload={downloadJobWork}
          onPreview={previewJobWork}
        />
      </div>
    </div>
  );
}
