-- Add document settings columns to company_settings
ALTER TABLE public.company_settings
  ADD COLUMN IF NOT EXISTS fy_year varchar DEFAULT '2526',
  ADD COLUMN IF NOT EXISTS invoice_prefix varchar DEFAULT 'INV',
  ADD COLUMN IF NOT EXISTS po_prefix varchar DEFAULT 'PO',
  ADD COLUMN IF NOT EXISTS dc_prefix varchar DEFAULT 'DC',
  ADD COLUMN IF NOT EXISTS grn_prefix varchar DEFAULT 'GRN',
  ADD COLUMN IF NOT EXISTS jc_prefix varchar DEFAULT 'WO',
  ADD COLUMN IF NOT EXISTS ao_prefix varchar DEFAULT 'AO',
  ADD COLUMN IF NOT EXISTS so_prefix varchar DEFAULT 'SO',
  ADD COLUMN IF NOT EXISTS dn_prefix varchar DEFAULT 'DN',
  ADD COLUMN IF NOT EXISTS fat_prefix varchar DEFAULT 'FAT',
  ADD COLUMN IF NOT EXISTS default_payment_terms varchar DEFAULT '30 days',
  ADD COLUMN IF NOT EXISTS default_terms_conditions text,
  ADD COLUMN IF NOT EXISTS default_bank_name varchar,
  ADD COLUMN IF NOT EXISTS default_bank_account varchar,
  ADD COLUMN IF NOT EXISTS default_bank_ifsc varchar,
  ADD COLUMN IF NOT EXISTS default_bank_branch varchar,
  ADD COLUMN IF NOT EXISTS show_logo boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_signature boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_not_for_sale boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_original_duplicate boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS default_footer_text text,
  ADD COLUMN IF NOT EXISTS signature_url varchar;
